### ISSUE TITLE
KML using <ui-gmap-layer>

### ISSUE THREAD

**Issue by dmackerman** [angular-ui/angular-google-maps#1046]
Trying to get a KML layer loaded, but it's throwing lots of digest errors. Seems like an infinite loop.

``` html
<ui-gmap-google-map center="vm.map.center" zoom="vm.map.zoom">
    <ui-gmap-layer type="KmlLayer" options="vm.overlayOptions"></ui-gmap-layer>
 </ui-gmap-google-map>
```

I set the `vm.overlayOptions` like so:

``` js
uiGmapIsReady.promise(1).then(function(instances) {
    vm.overlayOptions = {
        clickable: true,
        // url: 'images/outline.kml'
        url: 'http://gmaps-samples.googlecode.com/svn/trunk/ggeoxml/cta.kml',
        map: instances[0].map
    };
});
```

`instances[0].map` is the actual map object - but is it even required? If I remove it, nothing gets drawn anyway. 

```
 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
```

**Comment by dg1202** [comment]
Ever get anywhere with this? I am trying to do the same and cant get the layer to show. even after messing with the ng-google-maps lib.

**Comment by wrummler** [comment]
@dmackerman Did you reach any conclusion here on your own? If so, it'd be great to hear about it. If not, and if this is still an issue for you, please follow up with a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) demo'ing the behavior. Plunker is preferred, but anything you're comfortable with is also fine as long as it works. Thanks.

Btw, I have a very weak suspicion that it might have something to do with `vm.overlayOptions` not getting initialized by the `IsReady` callback before `ui-gmap-layer` tries to initialize with it, and then perhaps the latter chokes on an undefined (or otherwise invalid) options value. Don't know for sure at this point without an example.

@dg1202 If you could also provide an MCVE demo'ing the behavior you're observing, that'd be useful, too. Thanks.

**Comment by dmackerman** [comment]
Not sure what I did to solve this, or if I ever did. We were working on a small prototype, so it's entirely possible we trashed it. Sorry I can't provide any follow up. :cry:

**Comment by wrummler** [comment]
No problem, I'll go ahead and close this issue for now. But anyone else who'd like to follow up about it should feel free to. We can definitely reopen when we have an example to verify the behavior. Thanks.
