### ISSUE TITLE
Add polygon

### ISSUE THREAD

**Issue by knapeto** [angular-ui/angular-google-maps#1051]
Hey all,

I have problem with add new polygon to ui-gmap-polygons.

When I add new object example:

```
$scope.dynamicWaypointsData = [];
$scope.dynamicWaypointsData.push({
                        id: 10,
                        path: $scope.dynamicWaypointsList[eq].path,
                        clickable: true,
                        draggable: true,
                        editable: true,
                        visible: true,
                        geodesic: true
                    });
```

I have error in console TypeError: object is not a function

HTML:
```
<ui-gmap-polygons
                models="dynamicWaypointsData" path="'path'" stroke="'stroke'" visible="'visible'" geodesic="'geodesic'" editable="'editable'" draggable="'draggable'">
        </ui-gmap-polygons>
```

**Comment by aplus01** [comment]
Its tough to see where your issue is with fragments of markup and js. A plunker or something similar probably would make it more clear where the error lies.

Looks like your directive is set up properly in the markup. The only thing about your polygon models that looks odd to me is the path property. No way to know what that is getting set to based on what you've shared.

**Comment by nmccready** [comment]
@knapeto since we have not heard back from you; I am closing this issue.
