### ISSUE TITLE
Close X moved in an odd way using it for mobile

### ISSUE THREAD

**Issue by raiam12** [angular-ui/angular-google-maps#1126]
I am making an app and implemented this, the window from markers has a X to close, but the X is moving upper in the map, is there any way to add a custom X marker or class to avoid this behaviour.

**Comment by nmccready** [comment]
this is a google maps issue, it is your css framework mucking with google's css. Please search stackoverflow and google. There are many examples out there with bootstrap fixes that muck with the window . Lastly, if your issue is not resolved you will need to provide an example as the statement above provides us nothing to go on.
