### ISSUE TITLE
[r1-dev] How to trigger resize events on the underlying map instance?

### ISSUE THREAD

**Issue by fwitzke** [angular-ui/angular-google-maps#114]
Let's say I have a map is inside a div that takes 70% of the width and I want to dynamically change it to 100%. In this case I would need to notify the map it was resized:
`google.maps.event.trigger(map, 'resize');`

Any ideas on how to accomplish that?

[api reference:](https://developers.google.com/maps/documentation/javascript/reference)

> Developers should trigger this event on the map when the div changes size: google.maps.event.trigger(map, 'resize').

**Comment by 23tux** [comment]
@fbuskens Can you explain why this works?

**Comment by fbuskens** [comment]
hi 23tux

You can find an explanation here: https://niklausgerber.com/blog/responsive-google-or-bing-maps/

**Comment by nmccready** [comment]
Nice

**Comment by FlavorScape** [comment]
Using that strategy I can successfully resize the angular gmap container and the iframe responds accordingly. however, there is a visual defect in the actual map, it fails to load tiles beyond a certain bounds from the initialization size. My use case is I have a map widget inside a gridster draggable/resizable element. 

So, I have an interesting solution. Initialize the map's container size ``` .angular-google-map-container``` to a known value well above your max size. Then set your ```.google-maps:{width:100%;height:100%;``` etc so that it is liquid (the bounds of the actual map). Then set your overflow on the container to hidden.
