### ISSUE TITLE
`ui-gmap-markers` `fit="true"` attribute does not updates map center correctly

### ISSUE THREAD

**Issue by blckshrk** [angular-ui/angular-google-maps#1170]
Hi,

I get a bug on the master branch with `fit="true"` on `ui-gmap-markers`. At the map loading, the zoom is correctly update to fit bounds, but the center of the map isn't. It keeps the default set center.

I have to do a `fitBounds()` after a delay to override the center values.
```js
$timeout(function() {
    map.fitBounds(bounds);
}, 100);  
```

Thanks

**Comment by nmccready** [comment]
Did you test this against master?

**Comment by blckshrk** [comment]
Yes sir!

**Comment by nmccready** [comment]
Ok, any clue where the bug is? It would be in directives/api/map.coffee

**Comment by blckshrk** [comment]
No actually I don't take time to investigate more for the moment sorry :/

**Comment by nmccready** [comment]
Ok I think you need to go through the API and use set scope.bounds.

Us watching scope to set the maps bounds.
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/map.coffee#L257

The google events being watched to update scope to you.

https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/map.coffee#L128-L170

As you can see we do not track bounds on demand. We track it via idle. This is to avoid race conditions of all the other changing properties and to keep the scope from updating frequently. 

So we should possibly set scope.center after this [line](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/map.coffee#L257). What do you think?

**Comment by nmccready** [comment]
Did any of this help? It would be excellent if no changes are needed as I am hoping to release 2.0.13. ASAP

**Comment by nmccready** [comment]
So there is no `fit` attribute for the map. There is bounds, and if you set the bounds the map should fit to those bounds. If you use that then yes your scope center might not be in sync.  But it should update after idle.

**Comment by nmccready** [comment]
41ed765cba161549b0f5ccf168610047a10c8da0

**Comment by blckshrk** [comment]
Hi,

Sorry for the delay, I'm work on other features, so I didn't take time to check this.

Actually I do not explain my self correctly. I use the `fit` attribute of `ui-gmap-markers` like the following.

```html
<ui-gmap-google-map center="map.center" zoom="map.zoom">
    <ui-gmap-markers idKey="'bid'" models="markers" coords="'self'" doCluster="false" fit="'true'" icon="'icon'" events="markersEvents"></ui-gmap-markers>
</ui-gmap-google-map>
```

It was working on `2.0.9` if my memory is good.

**Comment by blckshrk** [comment]
I just try out the `2.0.13` and the bug is still here. The interesting fact is that it's working correctly when I click on cluster. It resizes correctly and fit perfectly. The bug appear at map loading or markers collection update.

**Comment by nmccready** [comment]
Ahh your original ticket did not specify markers anywhere. So I was looking into map bounds / fit only. Please be specific in the title and or original description.

**Comment by blckshrk** [comment]
Absolutely, it's my mistake. Sorry.
I edited thé thé title and my first post to be more specific.

**Comment by nmccready** [comment]
@blckshrk did you try using use fit="true" instead of fit=" 'true'"

**Comment by blckshrk** [comment]
Hi,

It do not work more better unfortunately (not in `2.0.13` or on `master`). The following code is working : 
```javascript
$q.all([uiGmapIsReady.promise(), $scope.beacons.$promise]).then(function(datas) {
    fitBounds(datas[0][0].map);
});

function fitBounds(map) {
    if ($scope.beacons.length <= 1) {
        return;
    }

    var bounds = new google.maps.LatLngBounds();
    for (var i = 0, beacon; beacon = $scope.beacons[i], i < $scope.beacons.length; i++) {
        bounds.extend(new google.maps.LatLng(beacon.latitude, beacon.longitude));
    }

    $timeout(function() {
        map.fitBounds(bounds);
    }, 100);
}
```

but if I use only this : 
```html
<ui-gmap-google-map center="map.center" zoom="map.zoom">
    <ui-gmap-window coords="map.window.model" options="map.window.options" closeClick="map.window.closeClick()" templateUrl="THEME_BASE + 'views/modules/beacons/templates/infowindow.tpl.html'" templateParameter="map.window"></ui-gmap-window>
    <ui-gmap-markers idKey="'bid'" models="beacons" coords="'self'" doCluster="false" fit="true" icon="'icon'" events="map.markersEvents" onClick="map.window.onClick()"></ui-gmap-markers>
</ui-gmap-google-map>
```

The centering do not work... Sorry I do not have much time to reproduce this in a Plunker (I'm not really  comfortable with Plunker).
I will try to take time this weekend to investigate (but you know deadlines and every thing...).

Thanks for your help!

**Comment by antoine64** [comment]
I reproduced the issue in Plunker : http://embed.plnkr.co/2EDlGMoEyVEIsd92Nob0
Markers are in USA and map center is set to France. Fit function doesn't center to USA markers.

This is very curious because it didn't work only with float longitude.
With an integer longitude, the map move its center correctly.

I found a solution, you have to set your markers at the uiGmapIsReady promise like this
http://embed.plnkr.co/nBR1ttQFWuWj1g2dfeTo

**Comment by armyofda12mnkeys** [comment]
I was able to reproducing 'fitting' not working in this plunker:
http://plnkr.co/edit/Lp061KkEiMaRIqKixCP8?p=preview
(there are 2 points, a standalone home location and then another marker).
If you uncomment and add the 2 extra points in the markers group it seems to work, but in my app sometimes 1 marker is returned.

I wonder if zoom and center should be required. 
Having a fit on the main   <ui-gmap-google-map> tag vs <ui-gmap-markers> might make more sense in case  you have to do something like i do where I set a different 'home' point via <ui-gmap-marker> then add <ui-gmap-markers>. 
Then fit on the main tag could figure out the bounds automatically (and zoom level since that shouldn't be hardcoded as well if using fit, since it may have to zoom out to a certain level to fit everything, right?).
center attr could be optional since you may want to zoom on the home location or maybe you can get a more optimal larger zoomed map but not having home always in the center.

That uiGmapIsReady promise temporary solution didn't work out for my plnkr.

-Arian

**Comment by th3m4ri0** [comment]
Thanks @antoine64, the uiGmapIsReady promise part is exactly what I needed.

**Comment by berendberendsen** [comment]
thanks @antoine64, you are a live saver. Changing it into integers made it work
