### ISSUE TITLE
Improve performance with markers

### ISSUE THREAD

**Issue by hgodoy** [angular-ui/angular-google-maps#1197]
Before all thanks for this great directive.
I need to add about 5000 markers to a map. I tried with less markers (about 2000) and it works better but passing that quantity using the map (zoom, move, scroll, ...) it becomes really slow. Is anything I can do?
Here is the code:
```
var markers = [];
	//loop array that contains data and location
	for(var i=0; i< $scope.clientes.length; i++){
		markers.push(crearMarcador(i));
	}
//create marker
	var crearMarcador = function(i){
		var marker = {
				id: i,
				idKey: "id",
				latitude: $scope.clientes[i].latitud,
				longitude: $scope.clientes[i].longitud,
				show: false,
				title: "<strong>Cod: </strong>" + $scope.clientes[i].codcliente +
	            		"<br><strong>Nombre: </strong>" + $scope.clientes[i].razonsocial + "<br><strong>Direccion: </strong>" + $scope.clientes[i].direccion
			};
			
		marker.onClicked = function(){
			marker.show = true;
			console.log('open: ' +  marker.show + ' title: ' + marker.title);
		    $scope.$apply();
		};
				
		marker.closeClick = function () {
		    marker.show = false;
		    console.log('close: ' +  marker.show);
	        $scope.$apply();
		};
		return marker;
	};
```

And the page:
```
<ui-gmap-google-map center='map.center' zoom='map.zoom' control="map.control">
	<ui-gmap-markers models="marcadores" coords="'self'" icon="'icon'" click="'onClicked'" >
		<ui-gmap-windows show="show" closeClick="'closeClick'">
			<p ng-non-bindable>{{title}}</p>
		</ui-gmap-windows>
    </ui-gmap-markers>
</ui-gmap-google-map>
```

**Comment by cthrax** [comment]
Do you need all 5000 windows open simultaneously? If not, use the 'window' directive as outlined in the FAQ, http://angular-ui.github.io/angular-google-maps/#!/faq "How do I only open one window at a time?" That could help with your performance.

**Comment by hgodoy** [comment]
Thanks for the quick answer, it improves the performance. The thing is that in the same map I have some editable polygons. And editing them is still slow. I found same behaviour in demo
http://angular-ui.github.io/angular-google-maps/#!/demo
If more than 2000 markers are added

**Comment by nmccready** [comment]
Did you disable or mess around with the chunking values?

**Comment by nmccready** [comment]
Also do you really need 5000 ~ 2000 markers at a time? Clustering helps but ultimately reducing the amount of markers rendered helps a lot. You can limit things to city and certain zoom levels with different behaviors. 

If you still need it all then someone is going to need to dig in and figure where the bottlenecks are. But honestly we may be approaching the limits of angular itself as we are doing a bunch of watching. The less watches the better. 

One problem could be that the markers are quazi duplicated in since there is an array of gMarkers in MarkerManager and markermodels (ChildModels w a ref to gMarker) in the ParentModel. Anyways with that in mind you O(2xN).. on some worst case scenarios.

**Comment by hgodoy** [comment]
I tried with clustering before and it works fine. My client wants to see all the markers, that is why I am trying but you're right zoom level cluster with different behaviors will be the one.

Thanks a lot.

**Comment by abachuk** [comment]
Marker display is delayed by around 1-2 seconds using Angular 1.2.27. I'm using just one map and one marker. Scrolling and all links become unavailable (the whole screen freezes) until marker is displayed. Has anyone experienced anything similar ?

**Comment by nmccready** [comment]
Are you using markers or marker directive. use markers and this should not be as much of an issue. There are things I can do at a later time to speed it up like (this)[https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletIterators.js] which gets us off some of lodash. This is because `for in` is way faster .

**Comment by nmccready** [comment]
I want to make a repo for the iterators library specifically and then wrap an angular version of it as well. It is on my things to do list.

**Comment by abachuk** [comment]
Im using ```<ui-gmap-marker>```, should I use ```<ui-gmap-markers>``` ?

**Comment by nmccready** [comment]
@abachuk most definitely; ui-gmap-marker is limited to ng-repeat / dom speed. Bottom line is terrible; in my mind it is deprecated but some people like using it for few markers or a small constant size. ui-gmap-markers or any plural directive is meant for small and large amounts. Please see documentation as it is not exactly the most angular implementation.

**Comment by nmccready** [comment]
http://angular-ui.github.io/angular-google-maps/#!/api/markers

**Comment by abachuk** [comment]
Thank you very much. This helps a lot!!!

**Comment by renege** [comment]
@nmccready that example is broken, can't see the output. but thanks anyways, i figured it out! loads much faster.

isn't there a good example somewhere? with marker with ```<ui-gmap-window>```?
