### ISSUE TITLE
Infoboxes remain visible when associated marker gets clustered

### ISSUE THREAD

**Issue by hohenseet** [angular-ui/angular-google-maps#1301]
Hi,
we are faced with the issue, that an <b>infobox</b> does not disappear when associated marker gets clustered.
The infowindow behaves perfectly, but it's not what we would like to use.

example can be found here: 
https://jsfiddle.net/mrgrafhh/kmrqj08w/3/

Thanks

**Comment by wrummler** [comment]
Both `InfoBox` and the clusterer are 3rd-party to AGM, so it seems likely that the clusterer was simply not designed with the `InfoBox` in mind.

That being said, perhaps it is still possible for something to be done to "integrate" them on AGM's side. I doubt it, but I'm not sure it can't be done.

**Comment by wrummler** [comment]
Closing this one since it's external. However, if anyone browsing this issue wants to investigate this and describe or develop a potential contribution that allows AGM to bridge the gap between these two external components (or provide any other useful details about the issue, really), that'd be welcome. You can follow up here. Thanks.
