### ISSUE TITLE
define marker icon as HTML

### ISSUE THREAD

**Issue by sivaboyapati** [angular-ui/angular-google-maps#1303]
I am trying to create a marker with an icon; Instead of passing an Icon image I would like to pass html tag;

How do I plot custom html marker on the google maps ?

![screen shot 2015-04-29 at 3 04 02 pm](https://cloud.githubusercontent.com/assets/7875023/7399067/1eabef40-ee81-11e4-9a38-59f047c2c96b.png)

**Comment by sivaboyapati** [comment]
I used the following code to get this working on using the gmap plugin; I would love to get this working using angular google maps plugin.

![screen shot 2015-04-29 at 3 16 18 pm](https://cloud.githubusercontent.com/assets/7875023/7399291/bae5a738-ee82-11e4-82f5-378ad7dade62.png)

**Comment by larsha** [comment]
Have a look here: http://angular-ui.github.io/angular-google-maps/#!/api and the parameters:

* labelContent
* labelAnchor
* labelClass

**Comment by wrummler** [comment]
@sivaboyapati In case your question was about the marker icon itself and not the label, I think you can use the regular [`google.maps.Icon` object spec](https://developers.google.com/maps/documentation/javascript/reference#Icon) as the format of the value of `icon` on the AGM marker directives. I haven't seen any examples doing this, but a quick look at the marker model's source gives me the impression.

If you still have any questions about this issue, please follow-up. If you can build a small example (using Plunker or JSFiddle or whatever you'd like) showing what you'd like to do and using the approach mentioned above, that'd be great since it would make the issue clearer and could make a potential feature addition (if applicable) more verifiable.

Closing for now. Thanks.
