### ISSUE TITLE
Enter key in a search box on a map inside a form provokes a button click event

### ISSUE THREAD

**Issue by caprica** [angular-ui/angular-google-maps#1306]
I am using a map and a search box inside a form.

If I press the enter key inside the search box embedded in the map, this somehow translates to a click event on the first button in the form.

See http://plnkr.co/edit/ibBOl5p8XH5PwAMeuDqH

With the console enabled, if you press the enter key in the search box you will see "I was clicked" appear in the log.

**Comment by kandizzy** [comment]
@caprica Wrapping the entire directive in a form means that the Google's SearchBox form is now nested. You can hack it to make it work by including a [dummy form](http://plnkr.co/edit/aCEaqr69VQYyLUTKpwxd?p=preview). It works, but it's bad practice. Can you structure your other form so that it does not wrap Google's forms? http://stackoverflow.com/questions/379610/can-you-nest-html-forms

**Comment by caprica** [comment]
Sure, I guess I can restructure. It was just very convenient to do it this way because of the natural/semantic flow of the elements in the page. Thanks for the tip.
