### ISSUE TITLE
angular-google-maps error when adding comments between the ui-gmap-window directive and the first division.

### ISSUE THREAD

**Issue by junit38** [angular-ui/angular-google-maps#1310]
This:
```
<!-- WINDOW -->
<ui-gmap-window options="windowOptions" closeClick="closeClick()">
    <!-- CONTENT -->
    <div></div>
</ui-gmap-window>
```
Show the window without content and give me this error:

```
Uncaught TypeError: Cannot set property 'opacity' of undefined                   angular-google-maps.js:2316
```

Work fine without the comment.

```
<!-- WINDOW -->
<ui-gmap-window options="windowOptions" closeClick="closeClick()">
    <div></div>
</ui-gmap-window>
```

**Comment by wrummler** [comment]
This occurs because the window directive uses only the first child element in its content. In this case, that's a comment element. See [the source](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/child/window-child-model.coffee#L174) and similar behavior re second point [here](https://github.com/angular-ui/angular-google-maps/issues/1340#issuecomment-108638059). The workaround is to place all the top-level elements of your nested template in a `div` and make that `div` the only child of the directive.

This is probably a worthy addition to the FAQ---and [done](https://github.com/angular-ui/angular-google-maps/wiki/FAQ#why-doesnt-my-ui-gmap-window-infowindow-with-a-nested-template-show-all-of-its-content).

**Comment by AlfonsoMonroyIV** [comment]
I have the same problem...does anyone have an idea?
        <ui-gmap-marker ng-repeat="m in map.markers" coords="m.coords" icon="m.icon" idkey="m.id" options="m.options" events="m.events">
          <ui-gmap-window options ="m.iW.options" />
      </ui-gmap-marker>

when i click on the marker... this message appears on console

angular-google-maps-street-view_dev_mapped.js:675 Uncaught TypeError: Cannot set property 'opacity' of undefined

**Comment by mohaideenisync** [comment]
@AlfonsoMonroyIV , Did you get any idea for your query.? I have same problem

**Comment by mluis** [comment]
Found [something](https://stackoverflow.com/questions/42343920/cannot-set-property-opacity-of-undefined-in-gmap-window) that seems accepted. Although is there any other or "proper" way of fixing it or is it a new feature?

Is there any other way of doing this?
