### ISSUE TITLE
Control functions not available at 'uiGmapGoogleMapApi' success

### ISSUE THREAD

**Issue by joshuahiggins** [angular-ui/angular-google-maps#1329]
This has been alluded to in a couple other issues:

* #1265
* #1243 

The suggested method fails unless using a `$timeout` wrapper, like so:

```
uiGmapGoogleMapApi.then(function () {
    $timeout(function(){
         var map = $scope.map.control.getGMap();
    });
});
```

You can see the issue in [this Plunkr](http://plnkr.co/edit/Hzdkd95wSd4bapy0Wv4Z?p=preview).

From poking around your code some, the high level view of the problem is that `GoogleMapApi` resolves on line 6159 and the promise fulfills itself at that moment. Anything that was relying on `uiGmapGoogleMapApi.then()` will execute before your code will proceed with the return function.

Not sure the best way to fix it, but I hope this helps!

**Comment by wrummler** [comment]
The `control` object is not guaranteed to be augmented until the `uiGmapIsReady` service's promise resolves. `uiGmapGoogleMapApi` is not meant to be used for this; it's meant to be used to signal when the Google Maps API has loaded (i.e. when the `google.maps` object is globally available).

#1265 mentions that `IsReady` was tried at first, but it seemed there were two errors there, (1) not initializing the `control` object to an empty object and (2) not using `IsReady`. If the OP was correctly using `IsReady` at first, it's likely the first error was screwing things up regardless. In their follow-up, they seem to have only tried `GoogleMapApi`, which is still incorrect.

#1243 seems to have been a user typo.

Your plunker encounters no errors if you
1. inject `uiGmapIsReady` instead of `uiGmapGoogleMapApi` and
2. replace `uiGmapGoogleMapApi` with `uiGmapIsReady.promise()`.

Updated [here](http://plnkr.co/edit/RJHN0SCFM6N1tDaFyFRC?p=preview).
