### ISSUE TITLE
[master][develop] Filtering markers throws exceptions

### ISSUE THREAD

**Issue by agaskell** [angular-ui/angular-google-maps#133]
In the example I added a search box:

```
<input type="search" placeholder="search" ng-model="query" >
```

And used this for markers:

```
<markers models="map.markers | filter:query" 
               coords="'self'" 
               click="'onClicked'"></markers>
```

The following exception gets thrown when I start typing:

```
Uncaught Error: 10 $digest() iterations reached. Aborting!
```

Am I doing something wrong?

**Comment by mdsEu** [comment]
still not working:

<ui-gmap-markers idkey="'id'" models="map.markers | mapFilterByCategories:categoryesToFilter" coords="'coords'" events="map.markersEvents" doCluster="flase"></ui-gmap-markers>

**Comment by wrummler** [comment]
`models` has to be an assignable Angular expression (think [L-value](https://en.wikipedia.org/wiki/Value_(computer_science)#Assignment:_l-values_and_r-values)) because [`Plural` uses bidirectional (`=`) binding for it](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/plural.coffee#L33). The result of a filter is basically an R-value i.e. not assignable.

I don't know a lot about the intricacies of AGM's models yet, but it doesn't seem like bidirectionality is necessary for this binding. I haven't found a place where AGM assigns to the `models` expression (but there's a chance I haven't looked hard enough). Even if it's handling updates to properties of the value that the expression evaluates to, that wouldn't require bidirectionality.
