### ISSUE TITLE
Jittery Panning in IE 11

### ISSUE THREAD

**Issue by charris-RA** [angular-ui/angular-google-maps#1342]
After recently updating I have noticed panning the map in IE 11 is extremely jittery now, even noticeable on the main page ( http://angular-ui.github.io/angular-google-maps/#!/ )..

**Comment by wrummler** [comment]
I'm not seeing this. All seems well and performant. I'm using latest IE 11 on Windows 7 64-bit. What did you update? AGM up to 2.1.1? Or IE? Or Windows? Have you cleared your browser cache etc?

**Comment by charris-RA** [comment]
AGM is 2.1.1, IE is latest.. I have checked on a few Windows 7 and 8.1 machines and it seems the jitteryness is limited to the Windows 8 machines.

**Comment by nmccready** [comment]
Have you tried disabling chunking on markers and or anything plural? If it is IE.. well I can't help sorry I dob't have the time to support IE right now.

**Comment by wrummler** [comment]
@charris-RA I've tested with IE 11 on Windows 8.1 64-bit. Still no issues. Just checking: When you say Windows 8, do you mean Windows 8.1 or the actual non-upgraded Windows 8?

In any case, you'll probably have to dig up more info about what's going on with those machines. For example: whether there are any error messages showing when you open up the F12 tools on the jittery page(s); whether the other browsers on the machines in question are showing odd behavior with AGM; etc.

Sorry in advance, since it seems unlikely a resolution will be reached.

**Comment by nmccready** [comment]
Have you played around with different versions of angular? I noticed 1.4 was avail through bower. I have not verified yet if this works with 1.4. So make sure your using 1.2-1.3.15

**Comment by charris-RA** [comment]
Sorry I should have been more specific, running Window 8.1 64-bit pro on the 3 computers I tested on, latest IE11.  Console isn't showing any errors, running the same page ( http://angular-ui.github.io/angular-google-maps/#!/ ) in chrome works flawlessly.

I have tried jumping back and fourth with different versions of angular with no avail.

I just forked someone else's plnkr so we have a baseline ( http://plnkr.co/edit/lBkiVLyDOaPUNlxdhsZi?p=preview ) and I am getting the jittery-ness when dragging the map in any direction.   

I really appreciate the help!

**Comment by wrummler** [comment]
Likewise, I forgot to mention that my tests were on 8.1 Home Edition. I don't have access to 8.1 Pro to test or try to reproduce any further.

It seems super-wyrd for this to happen only in IE and only on 8.1 Pro, but I suppose anything's possible. I'm sure you've already checked, but for the sake of completeness: does [regular old Google Maps](https://www.google.com/maps/) work as expected?

Do you observe any jitter on [Google Maps JS API sample pages](https://developers.google.com/maps/documentation/javascript/examples/)? Do you observe any jitter on other non-Google apps and pages that use only the Google Maps API? Do you observe any jitter on other apps and pages that use only Angular? You'll probably need to look around for examples.

Also, are you in a VM? Are there any other relatively "different" aspects like this about your systems' configurations? Most importantly, do you have access to configurations that are only very slightly different to try things out? Like 8.1 Pro outside of a VM? (If you're in a VM, that is...)

I know this is probably grasping at straws, but anything could end up being your ticket to a solution or workaround (or reproducible/fixable bug report, either here or elsewhere) in a case like this. It might end up more or less a goose chase...

I guess all I can say at this point is good luck! Hopefully it's something simple that was just overlooked.

Incidentally, `jittery-panning` sounds like the name of an Angular release...

**Comment by charris-RA** [comment]
Ya regular google maps works great in IE...  I am pretty baffled that it works with other versions of Windows 8.1... Something odd is going on possible related to our network AV just on Windows 8.1?

Google Maps JS API sample pages look good, just the angular google maps that freaks out..  

Something to note... (http://angular-ui.github.io/angular-google-maps/#!/api) going to the markers section the Maps doesn't even load in IE..

Not using any VM, might do some digging around the office and see if I can find anyone else using a different version of IE.

Appreciate the help and ideas!

**Comment by charris-RA** [comment]
Turned off security and connected via hotspot (outside network) issue still exists.

**Comment by nmccready** [comment]
What version?

**Comment by charris-RA** [comment]
Windows 8.1 Pro
IE 11.0.19

AGM: any
Angular: 1.2.26
Lodash: 2.4.1

Here is a plnkr with the latest AGM, where I encounter the issue.
http://plnkr.co/edit/lBkiVLyDOaPUNlxdhsZi?p=preview

**Comment by nmccready** [comment]
AGM any doesn't really help. I was mainly checking to see if it was an older one where some of the center watching caused jitteryness. But that was a while ago.

**Comment by charris-RA** [comment]
Sorry, I have encountered it on the most recent AGM releases... I am currently encountering it on the latest version 2.1.2

**Comment by nmccready** [comment]
If I were you I would put break point son the watches in the main map directive. See what is firing like crazy.

**Comment by wrummler** [comment]
@charris-RA Closing this one due to inactivity. Feel free to follow up with requested details. In particular, and I should've remembered this before, you might want to determine whether the three 8.1 Pro machines you tested on were on a particular network with (and I'm really just wildly speculating here) maybe some kind of network throttling or blocking on traffic to "uncategorized" IPs. My own network at work had a problem like this not too long ago.

Anyway, if you do find info that points to AGM, definitely let us know the details. If at all possible, an example and some reproducing instructions would be super appreciated. Thanks again for your report and for using the library.
