### ISSUE TITLE
How to pass marker model on click

### ISSUE THREAD

**Issue by dinodsaurus** [angular-ui/angular-google-maps#1351]
Im using controller as syntax so I need to bind this, but when I do that single marker model isn't passed to my click handler method. Any suggestions how to solve this ?

 `<ui-gmap-markers click="listController.markerClick(?).bind(this)" models="listController.list" coords="'coordinates'"></ui-gmap-markers> `

**Comment by nmccready** [comment]
It expects it to be a function where `.bind(this)` is returning something. Try
`<ui-gmap-markers click="listController.markerClick" models="listController.list" coords="'coordinates'"></ui-gmap-markers>` instead.

**Comment by dinodsaurus** [comment]
Then I can't access other methods from that class because `this` is `undefined`.

**Comment by nmccready** [comment]
Can you take care of the binding prior and then pass it the function? Why does this have to be done in the view?

**Comment by dinodsaurus** [comment]
Ok the situation looks like this:
```
<ui-gmap-markers 
  click="listController.markerClick"
  models="listController.list"
  coords="'coordinates'">
</ui-gmap-markers>
```
```
class listController{
  constructor(){}
  markerClick(marker){
    console.log(this);//returns undefined
    var type = marker.model.type;
   this.someOther(type);//error undefined
  }
  someOther(t){...}
}
```

And when I bind `this` like I showed earlier, I get the proper context of `this` and I can call other methods  but I can't get the marker model then.

**Comment by nmccready** [comment]
Please make a simple jsfiddle or plnkr and I will look at it. Fork this one http://plnkr.co/edit/u0KINZ4NTLyWqC0IeYwS

**Comment by dinodsaurus** [comment]
Ok will do it, unfortunately plunker has a bug with es6 but I have contacted the maintainer of it so I hope it will be fixed soon. When he fixes it I will ping you @nmccready :+1:

**Comment by nmccready** [comment]
Ok, jsfiddle?

**Comment by wrummler** [comment]
I made a fork to experiment with (just `markers` and `click`, no OP `listController` or ES6):
http://plnkr.co/edit/Kt9aWx6HWvISLJNrpgGl?p=preview

Since the `click` value is an event handler, it's called in the same way as the handler functions in the `events` attribute:

> Custom events to apply to the Marker. This is an associative array,
> where keys are event names and values are handler functions. See
> [Marker events](https://developers.google.com/maps/documentation/javascript/reference#Marker).
> 
> The handler function takes four parameters (note the args are
> expanding on the original google sdk's default args):
> 
> 1. Marker: the GoogleMaps Marker object
> 2. eventName: the name of the event
> 3. model: internal angular-google-map model being used to generate the google Marker object. This can be a model (plural directive) and or
> scope (singular directive).
> 4. arguments: the arguments provided by Google Maps for this event type. See [the Marker
> docs](https://developers.google.com/maps/documentation/javascript/reference#Marker)

@dinodsaurus, you should be able to just change the signature of `markerClick` to include the additional arguments it'll be given, and then use the `model` as provided.

    class listController{
      constructor(){}
      markerClick(marker, eventName, model) {
        console.log(model); // not undefined
        var type = model.type;
        this.someOther(type);
      }
      someOther(t) {...}
    }

To successfully reference `this.someOther` from `markerClick` when the latter is used in `click`, it does seem like some kind of `bind` action is necessary. However, when I attempt to use `bind` in the `click` expression as you illustrated, I get

> [$parse:isecff] Referencing call, apply or bind in Angular expressions is disallowed! Expression: mc.f.bind(mc)

As the example I made shows, I bound the method upon its (manual) export instead. Which is not equivalent to an ES6 class, I think, based on my cursory knowledge of ES6.

Since you seem to be able to use `bind` in your Angular expressions somehow, you might be good to go at this point.

(Incidentally, I've seen other people have problems with Angular 1.x when ES6 classes are directly used as Angular 1.x entities, i.e. controllers, directives, services. Might be wise in general to keep your Angular 1.x entities as plain functions a la ES5 and then let those functions' logic handle your ES6 classes etc.)

**Comment by nmccready** [comment]
Thanks @wrummler

**Comment by dinodsaurus** [comment]
Thanks for this writeup @wrummler :) , unfortunately I can't create angular with es6 on plunker but I will do a demo app and post a link to a repo latter.

**Comment by developersatish** [comment]
Hi I am adding this map on angular-bootstrap modal pop up and pushing marker value on button click,
but its not reflecting on map.
May i know the reason?

**Comment by nmccready** [comment]
@developersatish you need to provide more context and an example. Please provide a plunkr.

**Comment by wrummler** [comment]
@developersatish Please open a new issue when you follow-up. Please remember to include [an example that demonstrates the problem](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) as well as a detailed description of the problem so that we can help you in the best way possible. Thanks.
