### ISSUE TITLE
angular google map searchbox - places_changed is not called from the $route.current controller

### ISSUE THREAD

**Issue by gpositive** [angular-ui/angular-google-maps#1367]
I'm having an issue with angular google maps and the search box. Even if the ng-view onLoad works as expected, after typing in the search box, the places_changed callbacks are not called from the correct controller but only from the first one (and the default) defined in $routeProvider.

You can find more details below:

Part of the template:
```javascript
<div ng-controller="map">
    <div>
        <script type="text/ng-template" id="searchbox.tpl.html">
            <input type="text" placeholder="Search Place..." class="google-maps-search">
        </script>

        <ui-gmap-google-map center='map.center' events="map.events"  options="map.options" zoom='map.zoom'>
            <ui-gmap-search-box template="map.searchbox.template" events="map.searchbox.events" position="BOTTOM_RIGHT"></ui-gmap-search-box>
            <ui-gmap-marker coords="map.marker.coords" options="map.marker.options" events="map.marker.events" idkey="map.marker.id"></ui-gmap-marker>
            <ui-gmap-markers models="mapMarkers" coords="'self'" icon="'icon'">
                <ui-gmap-windows show="show">
                    <div ng-non-bindable>{{title}}</div>
                </ui-gmap-windows>
            </ui-gmap-markers>
        </ui-gmap-google-map>
    </div>

    <div><div ng-view="" onload="renderView()"></div></div>
```

Part of the parent controller:
```javascript
app.controller('map', function ($scope, $log, $location) {
    $scope.map = {
        events: {
            click: function(map, eventName, args) {}
        },
        marker:  {
            id: 0,
            coords: {
                latitude: $scope.lat,
                longitude: $scope.lng
            },
            options: { draggable: true }
        },
        searchbox: {
            template: 'searchbox.tpl.html',
            events: {
                places_changed: function (searchBox) {}
            }
        }
    };
});
```

And the following in each of the children controllers (defined in $routeProvider):
```
$scope.map.searchbox.events.places_changed = function (searchBox) {
    var place = searchBox.getPlaces();
    if (!place || place == 'undefined' || place.length == 0) {
        console.log('no place data :(');
        return;
    }

    $scope.lat = place[0].geometry.location.lat();
    $scope.lng = place[0].geometry.location.lng();
    $scope.map.center = {
        "latitude": $scope.lat,
        "longitude": $scope.lng
    };


    $scope.renderView();
};
```

Do you have any ideas?

**Comment by wrummler** [comment]
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it works.

I can't be sure without seeing a full example, but if `$scope.map.searchbox.events.places_changed` in your child controllers is using the exact same `$scope.map` object created in your parent controller, then I think I have an explanation:

The custom handler is added to the search box's model only when the search box is initialized, and the `events` object is not watched, so your later update to `events.places_changed` is not brought over to the search box's model.

I'm not sure of a nice way around this off the top of my head. You can grab the underlying SearchBox object in your initial handler and add your new listener then, but that might not be what you need or want.

If you'd like to contribute to this project, I can think of a couple things to explore:

1. In the search box's initialization, place an appropriate watch on the `events` object that will update the listener. You'd probably want to include logic to remove whatever previous handler was added from the `events` object.

2. Add a `control` parameter to the directive, like several other directives already have, so that you can add listeners manually.

hth

**Comment by wrummler** [comment]
I thought of something else. (Still assuming what I mentioned above.)

You could change your initial handler stub to something like

    events: {
      places_changed: function (searchBox) {
        return someService.placesChangedHandler(searchBox);
      }
    }

where you've appropriately injected `someService`, and in the child controllers (or other services etc) you've updated the `placesChangedHandler` property to the actual handler you want to be used.

This way you probably don't have to hack core :-)

**Comment by gpositive** [comment]
Hi wrummler,

Thanks a lot for your response.

You are right about the Plunker. You can find it here:
http://plnkr.co/edit/2yPCIaT516hnIX88Mcsh?p=preview

You can trigger the places_changed on the second page and you'll be able to reproduce what I'm getting.

Since I'm a newbie to angular and JS in general, I don't feel comfortable to contribute just yet but I'll be happy to do it in the future.

I still have to investigate your last response in which I don't have to hack core but I'm not sure on how exactly to achieve this. Could you edit the plunker I shared to give me a hint on what you mean (if that's easy for you)?

Also, correct me if I'm wrong, but this is an actual issue of the searchbox, right?

Thanks a lot

**Comment by wrummler** [comment]
What I described earlier is almost certainly happening, except that your first update to the handler is observed only because that update is evaluated before the [`$http.get` for the search box template](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/search-box.coffee#L41) inside the search box's initialization resolves its success callback (I'm pretty sure, at least; didn't play around too much on this one beyond verifying the behavior wasn't due to any delay in resolving the `GoogleMapApi` service/promise). That success callback is what completes the initialization of the search box.

So controller 1 initializes and does its update, then the search box initializes and picks up 1's previous update, then eventually controller 2 initializes and its update is never picked up into the search box model.

Here's an update demo'ing [my last suggestion](http://plnkr.co/edit/yk8wYH2APpcSjcQZqio1?p=preview).

> Since I'm a newbie to angular and JS in general, I don't feel comfortable to contribute just yet but I'll be happy to do it in the future.

I know exactly how you feel. I'd never written a line of JS in my life prior to about 8 months ago when work required it. What's more, I started at the same time with the notoriously slippery Angular :-) It's been quite an adventure. I like JS way more than I thought I would.

> Also, correct me if I'm wrong, but this is an actual issue of the searchbox, right?

I wouldn't call it a bug, since keeping a watch on the events attribute's object value is not a documented feature. (Granted also, its not a documented lack-of-feature, either.) Seems like a respectable feature request/suggestion, though. You could also contribute to the website docs to clarify this aspect for other users.

**Comment by wrummler** [comment]
Closing this one. Feel free to follow-up with details if the question wasn't answered. Thanks.
