### ISSUE TITLE
Dynamic content doesn't load properly on window with markers directive

### ISSUE THREAD

**Issue by knitzie** [angular-ui/angular-google-maps#1370]
Hi,
I just updated the angular-google-maps package on my project according to issue #354. 
Now I've got a strange behaviour: After first click on a marker, the window opens empty. On second click, the content is available.

I forked a matching fiddle and add a random variable (windowOptions.show) to the html content:
http://jsfiddle.net/martgvd0/

Context:
I am using the markers directive with window to display multiple markers and only one window at a time. The window should contain content from the marker, e.g. the address.

**Comment by mmacneil** [comment]
I updated to 2.5.1 yesterday and am using an identical setup (multiple markers w/ single window) and I am seeing the same behavior.  Additionally, I can only seem to bind a value from my selected marker model in the window IF I also bind to a property on windowOptions.  I'm sure this isn't it the only condition but seems related to this issue so I thought I'd mention it and it is demonstrated in in this fiddle: [http://jsfiddle.net/xpbu90mz/](http://jsfiddle.net/xpbu90mz/)  If you remove the binding in the window to 'windowOptions.show' the binding to MapOptions.markers.selected.coords.latitude never appears.

**Comment by wrummler** [comment]
@knitzie The click handlers in that fiddle are not correctly written or set up. It's also using an incorrect InfoWindowOptions object (see [spec](https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions); `show` is not part of it) in the `options` attribute on the window. After fixing the handlers and removing use of that attribute (and otherwise cleaning up), the fiddle works fine: http://jsfiddle.net/wrummler/443aaugr/

@mmacneil With the corrected fiddle, I can't reproduce the problem you've described.

If the problem persists in any way, feel free to follow-up with details and an updated example. Thanks.

**Comment by mmacneil** [comment]
Many thanks for setting me straight @wrummler - I've updated my project code accordingly and all good now.  

Thanks!
Mark

**Comment by knitzie** [comment]
Hi @wrummler, thank you very much :)
I'll set up your corrections in my project today
