### ISSUE TITLE
cordova +iOS Wifi not working but LTE does...

### ISSUE THREAD

**Issue by julesmoretti** [angular-ui/angular-google-maps#1372]
Hello there. First of all great plugin! Thank you for the time you guys spent to build this and the docs along with it.

I have implemented it using the instructions and when run on my local machine using grunt serve it work like a charm. When running Cordova emulate iOS no map gets loaded at all. And when loaded onto the iPhone everything works only if I am using LTE, if I close the app, turn wifi on and load the app again, it does not work. And the network seems to work properly too here. Tried it at my office and same issue.

Any insights on the matter would be amazing. Thank you!

**Comment by julesmoretti** [comment]
I added also the following to see if it ever gets alerted:

And in LTE mode it does pop up on the iPhone whereas when in WiFi mode it does not.

```
uiGmapGoogleMapApi.then(function(maps) {
          alert('google maps ready');
          ...
```

Now in my application.js file I have to following:

```
angular
    .module(ApplicationConfiguration.applicationModuleName, ApplicationConfiguration.applicationModuleVendorDependencies);

angular
    .module(ApplicationConfiguration.applicationModuleName)
    .config(['$locationProvider',
        function($locationProvider) {
            $locationProvider.hashPrefix('!');
        }
    ])
    .config(function(uiGmapGoogleMapApiProvider) {
        uiGmapGoogleMapApiProvider.configure({
            key: 'AValidGoogleMapsKey342n52jh5k2j4h5',
            v: '3.17',
            libraries: 'weather,geometry,visualization'
        });
    });
```

Any other tips would be awesome.

Thank you.

**Comment by wrummler** [comment]
Since it works without any problems on one network and it doesn't work on another network, it's probably the network.

I've experienced a similar problem before. I could connect my test device to either of two networks. One was more "corporate" than the other and had more firewall/proxy-type things configured for it. For some reason, over the course of a couple days, the Google Map tiles wouldn't load when I was connected to that network. The browser console would show tons of GET request errors against various Google tile servers. (By the way, all of these tile requests come from the Google Maps JS API's machinery, not AGM, which only wraps it with an Angular facade.)

And note your second test. Your observations mean that the Google Maps JS API never completes loading and the `uiGmapGoogleMapApi` promise consequently never resolves.

You might try configuring the AGM provider with no key, just for testing and just to see what happens. I'm guessing probably the same thing will happen, but you never know.

This is almost certainly a problem with the network. It's likely that Google's script is somehow, for some reason, being blocked on your network at the moment. Again, checking your browser console for error messages will shed light.

If you discover any evidence that it's a problem with AGM, please follow up with explicit details to support that claim and *very preferably* some way for us to see the same behavior ourselves, via an example and detailed instructions if at all possible.

Closing for now. Thanks.
