### ISSUE TITLE
Styling info window

### ISSUE THREAD

**Issue by badbod** [angular-ui/angular-google-maps#1392]
I cant see any way to specify a class or style for ui-gmap-window. Am I missing something?

**Comment by rootical** [comment]
So do I. Googling for 30 minutes already with no result.

**Comment by cthrax** [comment]
You need to set a template or templateUrl in order to customize the window.

**Comment by rootical** [comment]
@cthrax That's what I did, but what about pin, window box itself? It has it's own padding, sets rather unpredictable width and so on... Is there a way to get it done as if using `infoBubble`?

``` javascript

new InfoBubble({
      map: map,
      padding: 0,
      backgroundColor: 'rgb(57,57,57)'
});

```

**Comment by wrummler** [comment]
@rootical Based on some searching just now over [past issues](https://github.com/angular-ui/angular-google-maps/search?q=infobubble&type=Issues&utf8=%E2%9C%93), it looks like you might be able to do what you want by setting `boxClass` in the window directives' options object, which causes the directive to use `InfoBox` instead of `InfoWindow`. (See [the code that does this](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/child/window-child-model.coffee#L72-L77).) I'm not aware of any examples, unfortunately, and I myself have never used this aspect of the window directives before.

I don't think `InfoBubble` was ever integrated with AGM. There were at least a few comments about it in the past issues linked above, though.

**Comment by badbod** [comment]
@wrummler Many thanks. boxClass did the trick. I can now style all I want and animate the infoBox opening. I would like to animate the infoBox close too. Any ideas there would be much appreciated.

**Comment by baffleinc** [comment]
@badbod Just wondering how you used boxClass to achieve this? Added it in my `window`'s `options` object but no dice.

**Comment by netowp** [comment]
@baffleinc To get it to work, add a `boxClass` and a `boxStyle` to your `ui-gmap-window` options object, just like this:

```
$scope.map.window.options = {
    boxClass: "infobox",
    boxStyle: {
        backgroundColor: "#f9f9f9",
        border: "2px solid d9d9d9"
}
```
It should work.

**Comment by badbod** [comment]
wow, this is an old one. the map objects have boxClass so just add to your own CSS and make it do whatever you want.
