### ISSUE TITLE
map render problem in different tabs

### ISSUE THREAD

**Issue by uguryilmaz** [angular-ui/angular-google-maps#1395]
i have a tab control in my form. every tab page has its map object. first tab loads succesfully but maps in other tabs not loaded successfuly. here is plunker:

http://plnkr.co/edit/JUHRt5ogLcq0Eq6uo8n1?p=preview

**Comment by wrummler** [comment]
The behavior is caused by the maps in unselected tabs being rendered into hidden elements. The correct approach is to prevent map creation until the elements that will show it aren't hidden. You can use `tab`'s `active` attribute along with `ng-if` to help with this...

*However*, this is really strange because the [FAQ](http://angular-ui.github.io/angular-google-maps/#!/faq)'s recommendation to use `ng-if` doesn't seem to help. See updated plunker here: http://plnkr.co/edit/pmCPVhGeIPQnUFqmCcJF?p=preview

Not sure what the problem is. Hopefully I'm missing something obvious. @cthrax thoughts?

**Comment by cthrax** [comment]
The ng-if condition is changing in the same digest loop as the display of the tabs, so the DOM still hasn't had a chance to render. If you disconnect those conditions, which honestly feels a little weird semantically, it will render properly.

**Comment by wrummler** [comment]
Nice :+1: I've learned another nuance of Angular's digestion...

@uguryilmaz Follow up and reopen if this doesn't resolve the issue for you. Thanks.

**Comment by uguryilmaz** [comment]
thanks so much @cthrax and @wrummler . that solves my problem.

**Comment by nmccready** [comment]
:8ball:

**Comment by SunPj** [comment]
Sometimes just setting ng-if to true doesn't solve the problem. I use following code to refresh map.

```
$scope.showMap = false;
$timeout(function() {
    $scope.showMap = true;
});
````
