### ISSUE TITLE
Why? "unable to display a Google Maps element. See the Terms of Service"

### ISSUE THREAD

**Issue by renege** [angular-ui/angular-google-maps#1423]
I keep getting:
> This page was unable to display a Google Maps element. See the Terms of Service for more information: http://www.google.com/intl/en_US/help/terms_maps.html.

Why?
```
// Bower.json (partially)
{
  "dependencies": {
    "lodash": "~3.10.1",
    "angular": "1.4.3",
    "angular-google-maps": "~2.1.5"
  }
}

// Vendor.js (loaded first)
> Contains all JS from the Bower

// App.js (loaded after vendor.js)
var app = angular.module('app', ['uiGmapgoogle-maps']);
app.config(function(uiGmapGoogleMapApiProvider) {
    uiGmapGoogleMapApiProvider.configure({
        key: 'aaaaaa-2bPPq_7p_4Sk',
        v: '3.17',
        libraries: 'weather,geometry,visualization'
    });
})

// app.config(
//     ['uiGmapGoogleMapApiProvider', function(GoogleMapApiProviders) {
//         GoogleMapApiProviders.configure({
//             key: 'aaaaaa-2bPPq_7p_4Sk',
//             v: '3.17',
//             //libraries: 'weather,geometry,visualization'
//         });
//     }]
// );

// HTML view (for testing):
<ui-gmap-google-map center='{ latitude: 45, longitude: -73 }' zoom='8'></ui-gmap-google-map>
```

It does show the map, but after a while (when it's fully loaded I guess) I get the alert error and the map is gone.

This is also correct I guess? My local app is located at http://app.dev:8000/
<img width="866" alt="schermafdruk 2015-08-04 20 13 34" src="https://cloud.githubusercontent.com/assets/2900069/9068706/4f7effbc-3ae5-11e5-842c-68302e70493c.png">

**Comment by wrummler** [comment]
Your local app is truly local---we can't access it to check it out. You need to make a publicly accessible example (on Plunker or something like that) that demonstrates the problem.

(Incidentally, even if your referrers setting prevents others' use of your API key, you still shouldn't put your API key out in the open.)

With the information so far, it just looks like your site has gone past whatever usage quota is associated with your API key. That's not something we can help with.

Provide an example that clearly demonstrates the issue is due to AGM, and we can reopen this issue to help you out. Thanks.

**Comment by wrummler** [comment]
Also, note that the API key shown in your screen capture is *not* the same as the API key you're configuring AGM with... That might be it right there.

**Comment by renege** [comment]
@wrummler i scrambled the api key of course in both examples :) I pointed out what my local url is, because of the input at "referrers" in the Api console. So that's not the problem? 

So it isn't a regular/common alert that is shown?
