### ISSUE TITLE
Markers issue with latest version 2.1.5

### ISSUE THREAD

**Issue by maeishoj** [angular-ui/angular-google-maps#1429]
Hello everyone,

So i was using version 2.1.0 and all was well.
When I tried to use 2.1.5 I have the following problem: when I add markers I get this error:
"error within chunking iterator: TypeError: _.get is not a function"

Now the weirdest thing is that with the same code, if I import the 2.1.5 from here:

http://rawgit.com/angular-ui/angular-google-maps/2.1.5/dist/angular-google-maps.js

it works! 

I  both downloaded the .zip file and cloned it via git and point my app to the angular-google-map file version 2.1.5 and i always get that error.

Any clue why?

**Comment by wrummler** [comment]
Please make an example with Plunker and provide the link here. Construct it so that the issue can be toggled by simply editing a script element src attribute. Thanks.

**Comment by maeishoj** [comment]
Sure thing!

Please see here. I added the latest angular google maps 2.1.5 2015-07-28 and you can switch to the 2.1.5 from june instead in the html head.

http://plnkr.co/edit/Ebf7dk64PIIHvfMSKWlW?p=preview

**Comment by wrummler** [comment]
The issue is due to using lodash 2 rather than 3. There was a recent change to use _.get to access scope properties, and _.get is present only in lodash 3.7+. By switching your example's lodash, the issue goes away.

I think the released 2.1.5 (the one that worked for you and is available on the main website's front page) still lacks this change. The version number hasn't yet been bumped for it, but the change is on master, so when you download the zip or clone the repo. the change is there.

If you need to use the unreleased "edge" AGM rather than the released 2.1.5, you can switch to lodash 3.7+ (latest is 3.10.1).

Closing, but feel free to reopen if this problem persists. Thanks.

**Comment by maeishoj** [comment]
Super! Thanks!
