### ISSUE TITLE
ui-gmap-polylines - fit doesn't really work

### ISSUE THREAD

**Issue by flc** [angular-ui/angular-google-maps#1436]
when using the ui-gmap-polylines directive the `fit` parameter doesn't always work and the map does not fit its bounds around the all the polylines. it seems like in some cases it only tries to fit the last polyline but there are rare cases when it seems to work properly.
http://plnkr.co/edit/MReQdkryhwXJp2aMBOci?p=preview

**Comment by flc** [comment]
I'm almost certain now that it only takes into account the last polyline when it fits the map. I can hack around this by adding a dummy last polyline with a path that contains all points from all the polylines and set it's visibility to false via the visible param but then I realized that hidden polylines should be ignored when fitting the map.

**Comment by nmccready** [comment]
Confirmed also the code where the problem is obvious as each child is calling fit if it is defined. Therefore; as stated the last child gets the fit.

[Problem Lines](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/child/base-poly-child-model.coffee#L30-L33)

This instead should be called at the parent level and combine all path points instead.

**Comment by nmccready** [comment]
#1441 PR
