### ISSUE TITLE
Transition from 1.X to 2.X (Possible  Documentation Improvements)

### ISSUE THREAD

**Issue by tenaciousRas** [angular-ui/angular-google-maps#1488]
What good are commits such as #871 and #872 if the documentation is broken immediately?  Why doesn't the commit include the updated doc files, so nothing is broken when merged -- or at least why not open a new issue when the merge is completed since the docs are broken?  Do the current docs state that to include angular-google-maps in an Angular site running NG v.1.4.5 you need a line like this:

var myApp = angular.module('myApp', [''uiGmapgoogle-maps']);
??

Please excuse my sarcasm as the icing on this cake:  what was the awesome idea to change the module/provider name from google-maps/GoogleMapApi' to uiGmapgoogle-maps/uiGmapGoogleMapApiProvider ??  Nice naming convention...will a future update change the name to something like AngularNGUIGmapGoogleMaps-ByGoogle-Maps etc ?  Seriously let's tell EVERYBODY about the new name, I just spent way too much time tracking this name-change stuff down!

**Comment by nmccready** [comment]
because life isnt perfect; ill get to it

**Comment by cthrax** [comment]
@tenaciousRas mostly it's because there are 5000 unique users of the library every month and only one major contributor with 4 part timers doing all the work for the library. It's a LOT more useful if, when you see a deficiency, you say "here's a PR because I think it will help the project be better" then it is to file an issue "hey why would you do something so stupid".  Those of us that VOLUNTEER our time to contribute to this project obviously want the project to work as smoothly as possible, but there's not always time to get everything done.

I'm sorry you lost time investigating this, but frankly, issues like this do nothing but further prevent things getting done because it is highly demotivating to spend hours of one's free time, for other's benefit, only to receive negative feedback. Being frustrated is one thing, but try and be a bit more constructive, considerate and careful when commenting on other people's work.

**Comment by nmccready** [comment]
@tenaciousRas at first I thought you were insinuating that the website is down. But to get a better understanding; you are having a tough time from transitioning from 1.X to 2.X? 

I agree the name of `uiGmapgoogle-maps` blows goat;  but I am not about to go through the library and rename it for the sake of that. It is way too much code (project, wikis and website) to update at this point which will cause a 2.3.X for no good reason.

Anyway if you main issue is having problems from going from 1.X to 2.X.. well give back and provide some steps in the website, wiki, and or readme in this project. Otherwise your barking up the wrong tree.

**Comment by nmccready** [comment]
Closing unless something constructive is replied.

**Comment by tenaciousRas** [comment]
Our feelings are mutual, thanks for the pain, and thanks for not taking any
actions as a result - wise moves.

**Comment by nmccready** [comment]
Again your not being productive. If you don't like it please move on. Or propose changes with a PR and actually make an effort to fix the codebase. Come up with a solid solution with no sarcasm and them people will take you seriously. Otherwise your wasting everyone's time including yours. Start a new thread if you want and lets hope your positive about it. Otherwise please move on.
