### ISSUE TITLE
marker.options.visibile true/false not updating map

### ISSUE THREAD

**Issue by diego-betto** [angular-ui/angular-google-maps#1578]
Hi, 

I'm trying to show/hide group of markers using visibile attribute.
```
             $scope.$watch("myfilter", function(filt){
                myObjects.forEach(function (single) {
                    if (condition) {
                        single.options.visible = true;
                    } else {
                        single.options.visible = false;
                    }
                });
                $scope.mapOptions.control.refresh();
            },true); 
```

in view 
```
<ui-gmap-google-map center="mapOptions.center" zoom="mapOptions.zoom" events="mapEvents" control="mapOptions.control">
    <ui-gmap-markers models="myObjects" coords="'self'" events="markerEvents" options="'options'" doRebuildAll="true" modelsbyref="true"></ui-gmap-markers>
</ui-gmap-google-map>
```

myObjects is correctly updated, but markers are not hidden. 

Any idea?

**Comment by nmccready** [comment]
The code for this issue would all be in marker-child-model.coffee . My guess the settings are getting trumped by other digests. Also since there is the show attribute its probably a bug in deciding which to use. 

In realty getting rid of the show attribute would be best and rely on options soley as it is more flexible and less error prone.

**Comment by diego-betto** [comment]
My fault, options was declared as Array (so attributes were correct but length 0) and I think that nobody cares about empty arrays :D

Thank you for your tips and very quick response :)
