### ISSUE TITLE
search-box doesn't show up

### ISSUE THREAD

**Issue by DaSchTour** [angular-ui/angular-google-maps#1655]
I can't get the search-box to work. Including it in the map works as expected. But adding it to another div fails. There is no error but it simply doesn't show up. I guess the function for appeding it to the div is to restriced or something like this so that it doesn't find the div.

**Comment by kandizzy** [comment]
@DaSchTour Would you make an example of this problem in plunkr and post the link here?

**Comment by DaSchTour** [comment]
Here it is http://plnkr.co/edit/AoROGZjkR8bpTULZJNKE?p=preview

**Comment by kandizzy** [comment]
Thanks! Since `parentdiv` is an expression you can fix this issue in one of two ways.

---
You can define the `parentdiv` attribute as a string. http://plnkr.co/edit/8dXaDCl1Wkz4OAFY1pOs?p=preview

**in homepage.html**
`<ui-gmap-search-box parentdiv="'searchboxWrapper'"...`

---
Or you can define it in the `searchbox` obj in the controller and reference that property. http://plnkr.co/edit/7fkHlck5vphasxR5woZQ?p=preview

**in HomepageCtrl.js**
`vm.searchbox = { template:'searchbox.tpl.html', events:events, parentdiv:"searchboxWrapper"};`

**in homepage.html**
`<ui-gmap-search-box parentdiv="vm.searchbox.parentdiv"...`

**Comment by DaSchTour** [comment]
Oh okay. Wanted to make it too simple :D
