### ISSUE TITLE
How to hide the map from <ui-gmap-google-map>?

### ISSUE THREAD

**Issue by wolf00** [angular-ui/angular-google-maps#1667]
I only need the search box not the map. Can anyone tell me how to hide the map?

**Comment by nmccready** [comment]
Currently you can not due to this directive requirement. https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/search-box.coffee#L26

Therefore you might want to try CSS to hide it. 

Also anything in here that references gMap is also a dependency which would need to be modified to check for an optional `this.gMap` which currently is expected to always be there.

**Comment by wolf00** [comment]
I tried using CSS but it is hiding the searchbox as well because it is inside tag <ui-gmap-google-map>

**Comment by david-meza** [comment]
If you only want a search box, you don't need a directive. You can initialize it yourself and link it to any input box in your page. It is as easy as this:

    angular.module('yourApp').controller('yourCtrl', [ '$scope', 'uiGmapGoogleMapApi',
	  function ($scope, gMapsApi) {

    // Search box inside set my location panel
	  var autocomplete;
    
    // Function used by address typeahead on a place selected
	  var updateUserMarker = function() {
	    var loc = autocomplete.getPlace().geometry.location;
	    // Do something
	  };

	  gMapsApi.then(function(maps) {
	  	// Address typeahead
	    var input = document.getElementById('search-box');
	    var options = {};
	    autocomplete = new maps.places.Autocomplete( input, options );
	    autocomplete.addListener('place_changed', updateUserMarker);
	    
	  });

      }]);

**Comment by nmccready** [comment]
Good call @david-meza
