### ISSUE TITLE
Cluster icon removed 

### ISSUE THREAD

**Issue by amgadfahmi** [angular-ui/angular-google-maps#1848]
i have clustering enabled on thew map, ad suddenly the icons for the cluster is not shown, i tried HTTP and HTTPS but same result 

http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m1.png

**Comment by xavhan** [comment]
markerclusterplus changed their repo to github so the images are not hosted on googlecode.com anymore.
(cf . https://github.com/mahnunchik/markerclustererplus/commit/0f316e4bb91214f2fa9dc0e79779333b4044203a)
We need to update the dep

**Comment by amgadfahmi** [comment]
I have a system in production having this issue, is there anyway i can fix this until you guys update the dep !

**Comment by cthrax** [comment]
@amgadfahmi you can use clusterOptions to set a path to the images you want to use.

**Comment by xavhan** [comment]
```html
<ui-gmap-markers
      ...
      clusterOptions="{ imagePath: '//cdn.rawgit.com/mahnunchik/markerclustererplus/master/images/m' }"
      ... >
</ui-gmap-markers>
```

**Comment by amgadfahmi** [comment]
Thanks its working.

**Comment by mkeung** [comment]
I'm having the same issue in cordova. The above solutions aren't working on my end. Any ideas?

**Comment by davidpelayo** [comment]
I'm closing, therefore, this issue. (cc/ @amgadfahmi, @mkeung, @xavhan, @cthrax)

I also added [ISSUE_TEMPLATE.md](https://github.com/angular-ui/angular-google-maps/blob/master/ISSUE_TEMPLATE.md) so there explains how to report a potential bug better.

For the future, please provide detailed info, as per the ISSUE_TEMPLATE, including jsbins/plunkr/jsfiddle in order to help you better.

Thanks.
