### ISSUE TITLE
ng-click within windows

### ISSUE THREAD

**Issue by MauritzKruger** [angular-ui/angular-google-maps#356]
Good day Nicolas

I would like to know how I can use a controller function within the windows directive, tried code as mentioned for window, but did not work.

My markers change depending on search criteria and this is working as my markers increase/decrease depending on the criteria, and each markers info window is correct as well, just the click event that is not working.

My code:
HTML:
&lt;google-map center="mapObjects.center" zoom="mapObjects.zoom" draggable="true" options="mapObjects.options" control="mapObjects.control"&gt;
    &lt;markers ng-if="mapObjects.markers.length > 0" models="mapObjects.markers" coords="'self'" icon="'icon'" click="'onClicked'" labelContent="'title'" labelAnchor="22 0" fit="true"&gt;
        &lt;windows show="'showWindow'" closeClick="'closeClick'" options="mapObjects.windowOptions" ng-cloak&gt;
            &lt;p ng-controller="InfoWindowController"&gt;
                Borehole Name: {{windowInfo.boreholeName}}&lt;br/&gt;
                Area: {{windowInfo.area}}&lt;br/&gt;
                Sub Area: {{windowInfo.subArea}}&lt;br/&gt;
                &lt;a ng-click="viewDetails(windowInfo)"&gt;&lt;/a&gt;
            &lt;/p&gt;
        &lt;/windows&gt;
    &lt;/markers&gt;
&lt;/google-map&gt;

JavaScript:
angular.module( 'globalApp')
    .controller( 'InfoWindowController', function( $scope, $location ) {
        $scope.viewDetails= function() {
            console.log('GOES INTO FUNCTION'); //  Does not get here
        }
    });

**Comment by blckshrk** [comment]
An other way to get access to the parent controller functions is to put a reference to the `$scope` in the parameter object.

main.js
```javascript
$scope.map = {
    center: {
        latitude: 50.6278,
        longitude: 3.0583
    },
    zoom: 12,
    markersEvents: {
        click: function(marker, eventName, model) {
            if ($scope.map.window.model != model) {
                $scope.map.window.model = model;

                $scope.map.window.options.visible = true;
            }
            // toggle show/hide
            else {
                $scope.map.window.options.visible = !$scope.map.window.options.visible;
            }
        }
    },
    window: {
        model: {},
        closeClick: function() {
            $scope.map.window.options.visible = false;
        },
        options: {
            visible: false,
            maxWidth: 350
        },
        parent: $scope
    }
};
```

main.html
```html
<ui-gmap-google-map center="map.center" zoom="map.zoom">
    <ui-gmap-window coords="map.window.model" options="map.window.options" closeClick="map.window.closeClick()" templateUrl="template.html'" templateParameter="map.window"></ui-gmap-window>
    <ui-gmap-markers idKey="'pid'" models="pois" coords="'self'" events="map.markersEvents" onClick="map.window.onClick()"></ui-gmap-markers>
</ui-gmap-google-map>
```

template.html
```html
<div class="no-padding">
    <button ng-click="parameter.parent.delete(parameter.model)">Delete</button>
</div>
```

**Comment by vgrem** [comment]
Hello, 
recently i stumbled upon the same issue, the following solution worked for me:

First we need to introduce an additional controller:

    appMaps.controller('infoWindowCtrl', function($scope) {
       $scope.showInfo = function() {
          console.log('Button clicked!');
      }
    });

and then specify the following layout:

    <ui-gmap-windows show="show">
      <div ng-controller="infoWindowCtrl">
          <span ng-non-bindable>{{title}}</span>
          <button ng-click="showInfo()">Show info</button>
      </div>
  </ui-gmap-windows>



 

The same solution [has been posted in Stack Overlow](http://stackoverflow.com/a/33478657/1375553) 

[Working example](http://plnkr.co/edit/jO2nkIk1Nk2lu2wmRBlv?p=preview)

**Comment by ecbrodie** [comment]
$parent trick worked like a charm for me too! This seemed to be needed for any Angular attribute referencing a scope variable, such as ng-submit, ng-click and ng-model. Parsing of Angular placeholders (between double curly braces) seemed to be able to reference the scope variables, though.

On previous <ui-gmap-window> elements that I needed to parse attributes from scope variables, I found myself needing to create an Angular controller just for the window elements. I would then have to write glue code to pass data between my app's main controller and the nested controller for my window. This $parent solution was so much easier for me to use because I didn't have to introduce the new controller.

My main question is why exactly the $parent trick is needed. Is it because the code rendered from the <ui-gmap-window> template is somehow on a detached controller? Or something else specific?

**Comment by vargaendre** [comment]
Hi,

I just ran into this issue. I am using angular 1.5.3. with Ionic.
I have a ui-gmap-window next to a ui-gmap-markers element. I use templateUrl for the content and it has its own controller. None of the followings work: href, ng-href, hrefs with target=_blank, $parent, ng-click. The expressions get evaluated, so parameters turn into values, ng-href generates href attribute etc. I just can't make a single click event to work. This is quite frustrating, since this should be a simple task.
Any help is very much appreciated.

**Comment by vargaendre** [comment]
Okay, I found out, it works if I remove the `boxClass: "infobox"` from the options. Please, I really need the customizable looks, how can I solve this issue? Thank you

**Comment by vargaendre** [comment]
OK, so I figured it out. You need to add `enableEventPropagation: true` to the options to enable click events. For the record.
