### ISSUE TITLE
HTML embeded coordinates

### ISSUE THREAD

**Issue by bjorkblom** [angular-ui/angular-google-maps#418]
When setting map coords embeded in HTML, and resizing the window I get the following exception.

`Error: [$compile:nonassign] Expression '{ latitude: 56.1605, longitude: 15.5871 }' used with directive 'googleMap' is non-assignable!`

Code:

``` html
<div class="wrapper" google-map center="{ latitude: 56.1605, longitude: 15.5871 }" zoom="14" options="{scrollwheel: false}">
    <div marker icon="'/Content/img/google_maps_pin_site.png'" coords='{latitude: 56.1605, longitude: 15.5871}' click="openURL('http://www.google.com')"></div>
    <div marker icon="'/Content/img/google_maps_pin_site.png'" coords='{latitude: 56.1605, longitude: 15.5824}' click="openURL('http://www.google.com')"></div>
    <div marker icon="'/Content/img/google_maps_pin_site.png'" coords='{latitude: 56.1576, longitude: 15.5872}' click="openURL('http://www.google.com')"></div>
    <div marker icon="'/Content/img/google_maps_pin_site.png'" coords='{latitude: 56.15726, longitude: 15.5928}' click="openURL('http://www.google.com')"></div>
</div>
```

**Comment by heldrida** [comment]
Unfortunately I'm having to define as a string on the view, because I'm working with a server-side cms project. At the moment the best way to work with the cms, is having it render the properties server-side as a string. I'm trying your suggestion about ng-init but the map is not generated

<div ui-gmap-google-map ng-init="center = {  latitude: 51.4994961, longitude: -0.1246853 }"  >

Mind having a look ?
