### ISSUE TITLE
Map not fully loading

### ISSUE THREAD

**Issue by RomainGoncalves** [angular-ui/angular-google-maps#863]
Hey guys,

I'm using the map in a very simple way. I have the following HTML:

``` html
<ui-gmap-google-map center="map.center" zoom="map.zoom" pan="'true'">
        <ui-gmap-marker
          idKey="marker.idKey"
          coords="marker.coords"
          options="marker.options"
          icon="marker.icon">
        </ui-gmap-marker>
</ui-gmap-google-map>
```

and js:

``` javascript
$scope.map = {
    center: {
      latitude: -8.19,
      longitude: 115.5
    },
    zoom: 9
  };

  $scope.marker = {
    idKey: 1,
    coords: {
      latitude: -8.5831156,
      longitude: 116.2729975
    },
    icon: 'http://localhost:9000/images/icons/rsz_map-marker.png',
    options:{
      draggable: true
    }
  };
```

So my issue is that the map is only loading/showing one tile. The one on the top left. The others load only if I resize the window. I can zoom and drag the map, but the tiles don't load.

Thanks for any help.

**Comment by mcverter** [comment]
I am having the render problem as well, but there is not an explicit ng-show involved.  What I do have in this case is a tabbed view, in which one tab shows a list, one tab shows a map, and one tab shows a calendar.  

I have remedied the situation by wrapping the map in a <div ng-if="showMap"> and a <button ng-click="showMap=true>showMap</button>

But this is a bit of a hack.  

Any ideas?  Is there an implicit show/hide in the tab control that I can explicitly add to my controller instead of doing the button workaround?

**Comment by nmccready** [comment]
Please read and check around but the problem is google. If the map is hidden in anyway it needs to be notified to resize. ng-if is one workaround and or hack. The other is to explicitly tell the map to resize (search google). 

There is an existing issue, where I tried to make it cleaner by using ng-init but the end I gave up. However, using ng-init on your end (controller) probably is the cleanest way. By all means try to find a better way.

**Comment by nmccready** [comment]
#639

**Comment by nmccready** [comment]
#603

**Comment by nmccready** [comment]
#503

**Comment by nmccready** [comment]
#1056

**Comment by nmccready** [comment]
Here is the main one I wanted everyone to see #1114

**Comment by mcverter** [comment]
Thanks for your reply.  I figured out a better workaround right after
posting -- namely, attach an ng-model to the tab controls.
I've had the same problem, of the map only partially rendering, in other
contexts.
Thanks for looking into it!

**Comment by AnthonyCorrado** [comment]
Thanks everybody for the simple explanation and solution in ng-if. Big time thanks to RomainGoncalves for making it even easier!

**Comment by Denich** [comment]
Thanks @RomainGoncalves, ng-if workaround solution has helped me.

**Comment by panconjugo** [comment]
how did you guys solve it using ng-if? any sample?

**Comment by mcverter** [comment]
Hi all,

I am wondering whether there is an IETF standards document with standards
for how to encode geolocation information.

I know googlemaps has an API but I am looking for an RFC, like this one for
calendars:

https://tools.ietf.org/html/rfc5545



-- 
------------------

How can I
......explain
............to you
my state of mind?
The earth
has a whole skyful of lights...
The blue sky,
......a hell of a lot
............of stars.

Vladimir Mayakovsky

**Comment by sg28** [comment]
I was introducing the map into a modal ,SO it loaded the first time i open the modal but then it was not doing it the next time.
It seemed to work with the ng-init for now,Is ng-init a hack? am curious!

**Comment by nicosampler** [comment]
I found a cleaner solution here: https://github.com/angular-ui/angular-google-maps/issues/1114#issuecomment-72940314
